// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

export interface BaseModel {
  id: number /* uint */;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}
export interface User extends BaseModel {
  name: string;
}
export interface ContactMethod extends BaseModel {
  user_id: number /* int64 */;
  type: string;
  value: string;
  description: string;
}
export interface Reminder extends BaseModel {
  user_id: number /* int64 */;
  river_job_id: number /* int */;
  contact_method_id: number /* int64 */;
  body: string;
  start_time: string;
  is_repeating: boolean;
  period_minutes: number /* int64 */;
}
