// Code generated by tygo. DO NOT EDIT.

//////////
// source: clerk_protocol.go

export interface ClerkEvent {
  type: string;
}
export interface ClerkUserCreatedEvent {
  data: ClerkUserData;
  event_attributes: EventAttributes;
  object: string;
  timestamp: number /* int64 */;
  type: string;
}
export interface ClerkUserData {
  birthday: string;
  created_at: number /* int64 */;
  email_addresses: EmailAddress[];
  external_accounts: any[];
  external_id: string;
  first_name: string;
  gender: string;
  id: string;
  image_url: string;
  last_name: string;
  last_sign_in_at: number /* int64 */;
  object: string;
  password_enabled: boolean;
  phone_numbers: any[];
  primary_email_address_id: string;
  primary_phone_number_id?: string;
  primary_web3_wallet_id?: string;
  private_metadata: { [key: string]: any};
  profile_image_url: string;
  public_metadata: { [key: string]: any};
  two_factor_enabled: boolean;
  unsafe_metadata: { [key: string]: any};
  updated_at: number /* int64 */;
  username?: string;
  web3_wallets: any[];
}
export interface EmailAddress {
  email_address: string;
  id: string;
  linked_to: any[];
  object: string;
  verification: Verification;
}
export interface Verification {
  status: string;
  strategy: string;
}
export interface EventAttributes {
  http_request: HTTPRequest;
}
export interface HTTPRequest {
  client_ip: string;
  user_agent: string;
}

//////////
// source: protocol.go

export interface CreateReminderRequest {
  body: string;
  start_time: string;
  is_repeating: boolean;
  period_minutes: number /* int64 */;
  contact_method_id: number /* int64 */;
  phone_number?: string;
  email?: string;
}
export interface Reminder {
  id: number /* int64 */;
  user_id: number /* int64 */;
  body: string;
  start_time: string;
  is_repeating: boolean;
  period_minutes: number /* int64 */;
  contact_method_id: number /* int64 */;
  phone_number?: string;
  email?: string;
}
export interface ContactMethod {
  id: number /* int64 */;
  user_id: number /* int64 */;
  type: string;
  value: string;
  description: string;
}
export interface CreateContactMethodRequest {
  type: string;
  value: string;
  description: string;
}
export interface UpdateContactMethodRequest {
  type: string;
  value: string;
  description: string;
}
export interface UpdateReminderRequest {
  body: string;
  start_time: string;
  is_repeating: boolean;
  period_minutes: number /* int64 */;
  contact_method_id: number /* int64 */;
  phone_number?: string;
  email?: string;
}
export interface DeleteResponse {
  message: string;
}
export interface ErrorResponse {
  error: string;
}
export interface GetRemindersQuery {
  include_past: boolean;
}
