// Code generated by tygo. DO NOT EDIT.

//////////
// source: protocol.go

export interface CreateReminderRequest {
  user_id: number /* int64 */;
  body: string;
  start_time: string;
  is_repeating: boolean;
  period_minutes: number /* int64 */;
  contact_method_id: number /* int64 */;
  phone_number?: string;
  email?: string;
}
export interface Reminder {
  id: number /* int64 */;
  user_id: number /* int64 */;
  body: string;
  start_time: string;
  is_repeating: boolean;
  period_minutes: number /* int64 */;
  contact_method_id: number /* int64 */;
  phone_number?: string;
  email?: string;
}
export interface ContactMethod {
  id: number /* int64 */;
  user_id: number /* int64 */;
  type: string;
  value: string;
  description: string;
}
export interface CreateContactMethodRequest {
  user_id: number /* int64 */;
  type: string;
  value: string;
  description: string;
}
export interface UpdateContactMethodRequest {
  type: string;
  value: string;
  description: string;
}
export interface UpdateReminderRequest {
  user_id: number /* int64 */;
  body: string;
  start_time: string;
  is_repeating: boolean;
  period_minutes: number /* int64 */;
  contact_method_id: number /* int64 */;
  phone_number?: string;
  email?: string;
}
export interface DeleteResponse {
  message: string;
}
export interface ErrorResponse {
  error: string;
}
export interface GetRemindersQuery {
  user_id: number /* int64 */;
  include_past: boolean;
}
export interface GetContactMethodsQuery {
  user_id: number /* int64 */;
}
